import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import fullColorLogo from '../public/logo-full-color.png';
import { useAuth } from '../providers/auth';

export default function Home() {
	const { login, createAccount } = useAuth();
	return (
		<div className={styles.container}>
			<Head>
				<title>Explore bulb</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/bulb-favicon.ico' />
			</Head>

			{/* Testing the login function. TODO: Delete this */}
			<button
				onClick={() =>
					login('thekirkconcept@gmail.com', 'password1234')
				}
			>
				Login
			</button>
			{/* Testing the create account function. TODO: Delete this */}
			<button
				onClick={() =>
					createAccount(
						'Christopher',
						'Jones',
						'thekirkconcept@gmail.com',
						'password1234',
					)
				}
			>
				Create Account
			</button>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Get Started With <b>bulb</b>💡
				</h1>
			</main>

			<footer className={styles.footer}>
				<span className={styles.logo}>
					<Image
						src={fullColorLogo}
						alt='bulb Logo'
						width={144}
						height={64}
					/>
				</span>
			</footer>
		</div>
	);
}
