import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.sass';
import fullColorLogo from '../public/logo-full-color.png';
import { useState } from 'react';

export default function Home() {
  const [ isMenuActive, setIsMenuActive ] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Explore bulb</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/bulb-favicon.ico' />
      </Head>

      <main className={`${styles.main} ${isMenuActive ? styles.inactive : ''}`}
            onClick={() => setIsMenuActive(!isMenuActive)}>
        <h1 className={styles.title}>
          Get Started With <b>bulb</b>💡
        </h1>
      </main>

      <footer className={styles.footer}>
        <span className={styles.logo}>
          <Image src={fullColorLogo} alt='bulb Logo' width={144} height={64} />
        </span>
      </footer>
    </div>
  );
}
